version: 0.2 

phases: 
  install:
    runtime-versions:
      docker: 18
  pre_build: 
    commands: 
    - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 143287522423.dkr.ecr.us-east-1.amazonaws.com/todosrus
  build: 
    commands: 
    - docker build -t todosrus . 
    - docker tag todosrus:latest 143287522423.dkr.ecr.us-east-1.amazonaws.com/todosrus:latest
  post_build: 
    commands: 
    - docker push 143287522423.dkr.ecr.us-east-1.amazonaws.com/todosrus:latest